florent37/Flutter-AssetsAudioPlayer

ios/Classes/SwiftAssetsAudioPlayerPlugin.swift
Just copying the fix from [here](https://github.com/florent37/Flutter-AssetsAudioPlayer/issues/1#issuecomment-507635139) because I was trying to use this library on iOS.
=> Fix "resource not found" on iOS

android/src/main/kotlin/com/github/florent37/assets_audio_player/notification/NotificationService.kt
This PR fixes issue with an extra separator in the notification, when the `album` name is null or empty.
=> fixes showing of subtext separator in notification

android/src/main/kotlin/com/github/florent37/assets_audio_player/notification/NotificationService.kt
This PR fixes showing of notification published time, technically `setWhen` method. 
The "now" in notification doesn't make sense for an audio playing notification. Usually `when` is used to show elapsed time of notification was displayed.
=> update: hide published time in notification

CHANGELOG.md, assets_audio_player_web/lib/web/web_player_html.dart, assets_audio_player_web/pubspec.yaml, pubspec.yaml
Fixes https://github.com/florent37/Flutter-AssetsAudioPlayer/issues/194
@florent37 I have bumped the version and added the changelog.
You can tweak it if required.
Also are you sure this seconds/milliseconds conversion problem is not happening elsewhere?
=> Fix seek on web

lib/src/assets_audio_player.dart, lib/src/network_settings.dart
In my case, I had to add headers to each audio object, but the 'Authorization' header was expiring after a few minutes, because of that in the playlist the audio objects were no longer valid after some time. Instead of changing every audio object, all you have to do is change only the default headers for each object. 
The settings so far are poor - only headers, but it's easily expandable to other features like error-handling.
=> added centralized way to set network headers

lib/src/assets_audio_player.dart
@florent37 
I tried to fix this one i found that the player should be created only when the isBuffering is false or the player is stop state.
Please look into the PR and see if this make sense.
I have tested livestream and @johnny-stevie  has tested other playing features network assets and local. 
mentioning issue #290
=> Fix Parralel Audio Playing on spamming notifications next,previous & play buttons or calling play multiple times.

lib/src/assets_audio_player.dart
I has a requirement to send headers to the server during audio fetching via AudioType.network. While cross-checking the code, I found AudioType.network was missing while centralizing the headers. Hence, I added the same to the existing condition. Now the headers are working fine for me.
The reason for omitting AudioType.network in while centralizing headers is unknown.
=> Included AudioType.network networkHeaders

lib/src/notification.dart
CustomPrevIcon was not working due to missing lines in notification.dart. It is solved by adding this two lines. When we unable all the notification bar setting in our flutter project it shows a constant error CustomPrevIcon not found. When checking the Notification.dart file I found this two lines missing.
=> CustomPrevIcon fixed

README.md
There was a missing class name in the example which is in AudioWidget section.
=> A missing class name was added to README.md file.

darwin/Classes/Music.swift
```
error: 'TimeControlStatus' is only available in macOS 10.12 or newer
```
fixes https://github.com/florent37/Flutter-AssetsAudioPlayer/issues/391
=> Add conditional check for timeControl (macOS)

darwin/Classes/Music.swift
After testing the latest 2.0.13 release which included a fix that enables the seekbar to ios users I encountered a bug.
The Elapsed Playback Time in the notification seekbar was incorrect (it was jumping every 10 minutes rather than every second)
This PR should fix this issue and show correctly the current playback position.
=> Set correct property elapsed playback time

darwin/Classes/Music.swift
On iOS 10+ add playImmediately to avoid unnecessary delay when playing
=> Remove delay when playing on iOS 10+

darwin/Classes/Music.swift
```
.pub-cache/hosted/pub.dartlang.org/assets_audio_player-3.0.3+2/darwin/Classes/Music.swift:612:25: 
Initialization of variable 'error' was never used; 
consider replacing with assignment to '_' or removing it
```
Solution was to remove it.
=> Fix Swift Compiler Warning - unused Music.swift variable

darwin/Classes/Music.swift
1、assetsAudioPlayer.open api set autoStart and playSpeed is not work
2、playSpeed = 0.5 distortion of sound
=> fix: assetsAudioPlayer.open  playSpeed is not work

README.md, android/src/main/kotlin/com/github/florent37/assets_audio_player/AssetsAudioPlayerPlugin.kt, android/src/main/kotlin/com/github/florent37/assets_audio_player/Player.kt, android/src/main/kotlin/com/github/florent37/assets_audio_player/playerimplem/PlayerImplem.kt, android/src/main/kotlin/com/github/florent37/assets_audio_player/playerimplem/PlayerImplemExoPlayer.kt, android/src/main/kotlin/com/github/florent37/assets_audio_player/playerimplem/PlayerImplemMediaPlayer.kt, lib/src/assets_audio_player.dart, lib/src/playable.dart
**Additions**
- `setPitch` method to the `AssetsAudioPlayer` class, for changing pitch of the audio playback.
- `pitch` optional argument to `open` method of the `AssetsAudioPlayer` class.
**Notes** 
- A change has been made to `setPlaySpeed` (in `PlayerImplemExoPlayer`) method aswell, so as to ensure proper functioning. Alternative `PlaybackParameters` constructor is used now to enable pitch control aswell (More on that [here](https://exoplayer.dev/doc/reference/com/google/android/exoplayer2/PlaybackParameters.html#%3Cinit%3E(float,float))).
- This only works for Android, firstly because iOS does not have any equivalent, secondly I don't own a macOS running machine.
**Example**
Takes `pitch` as an argument, clamped between `0` & `16` just like `setPlaySpeed`.
```dart …
```
=> [android] Added setPitch method

darwin/Classes/Music.swift
Fixes https://github.com/florent37/Flutter-AssetsAudioPlayer/issues/644.
=> Add availability check to fix build for macOS

darwin/Classes/Music.swift
The problem was that mp3 files from urls without extension were not played on iOS but on android they were. 
The following error message was thrown: `flutter: PlatformException(PLAY_ERROR, Cannot play https://{server-url}/files/8be4af2f-2c96-44ef-afcc-393267f2fc34, Cannot Open, null)`
With the change of the MIME type in the AVURLAsset from "mp3" to the correct MIME type "audio/mpeg" the files are now also played under iOS.
=> #246: correct MIME-Type from "mp3" to "audio/mpeg""

assets_audio_player_web/lib/web/assets_audio_player_web.dart
Package can be null, but was not nullable in platform call to open.
=> Fix web play null error - Issue 654

android/build.gradle
https://blog.gradle.org/jcenter-shutdown
jcenter is shutting down and this can cause Android build failures in some regions atm, and globally in the future.
=> Prefer mavenCentral for Android builds.

README.md
Inside Readme.md in line 
> Make sur you added those icons inside your `android/res/drawable` **!!! not on flutter assets !!!!**
Replace **sur** with the word **sure**
> Make **sure** you added those icons inside your `android/res/drawable` **!!! not on flutter assets !!!!**
=> Fix Typo in Readme.md Line number : 502

assets_audio_player_web/android/build.gradle
We were forced to raise the `gradle` version (as many probably did), but `assets_audio_player_web` contains an old version of `kotlin` - so this error occurs
```error
FAILURE: Build failed with an exception.
* What went wrong:
The Android Gradle plugin supports only Kotlin Gradle plugin version 1.5.20 and higher.
The following dependencies do not satisfy the required version:
project ':assets_audio_player_web' -> org.jetbrains.kotlin:kotlin-gradle-plugin:1.3.50
```
This little PR fixes that problem
=> Bump kotlin version

android/build.gradle, android/gradle/wrapper/gradle-wrapper.properties, assets_audio_player_web/android/build.gradle, assets_audio_player_web/android/gradle.properties, assets_audio_player_web/android/gradle/wrapper/gradle-wrapper.properties
In a project I can't update from gradle `7.2.2` to `7.3.1` because of the old kotlin version of `assets_audio_player_web`.
This PR updates all dependencies that Android Studio showed and removes one deprecated line.
@kalismeras61 just saw that there already was a [merged PR](https://github.com/florent37/Flutter-AssetsAudioPlayer/pull/730). Could you please publish new versions?
And I think it can't hurt to bump the dependencies to the latest stable versions, as in this PR - if they're working correctly 😊
=> Update gradle and gradle plugin, apply Android Studio suggestions

example/android/app/src/main/AndroidManifest.xml
Deletes deprecated splash screen meta-data element in example app.
This is no longer needed to present a splash screen in a Flutter application, but may cause a crash. Please see [Deprecated Splash Screen API Migration Guide](https://docs.flutter.dev/development/platform-integration/android/splash-screen-migration) for more information.
=> [Android] Remove deprecated splash screen meta-data element

android/build.gradle, android/gradle.properties, android/gradle/wrapper/gradle-wrapper.properties
Thanks for this project. 
I use this package in one of work projects and recently bumped into an issue that Android builds started to fail after I tried to remove [Jetifier](https://developer.android.com/studio/command-line/jetifier) from the project as thought that all dependencies already switched to AndroidX. 
As it turned out `asset_audio_player` had old `support` multidex dependency. In this PR I switched to newer version, which is already an AndroidX dependency, thus, would allow to also drop `android.enableJetifier=true` as Jetifier has effect on incremental build speed: https://adambennett.dev/2020/08/disabling-jetifier/
Finally, did some minor version updates and dropped redundant `kotlinx-coroutines-core` dependency as `kotlinx:kotlinx-coroutines-android` is enough for Android …
=> Switch to AndroidX, drop Jetifier, update Kotlin dependencies

android/src/main/kotlin/com/github/florent37/assets_audio_player/notification/ImageDownloader.kt
i faced a crash when i start an audio using file constructor 
and i am with no internet 
when i pause the audio then connect device to internet the app crashes 
when i logged the error i faced Already resumed in glide so i tried to handle this to not throwing an unhandled exception
by wrapping with if condition
=> Glide exception already resumed crash

README.md, analysis_options.yaml, assets_audio_player_web/analysis_options.yaml, assets_audio_player_web/pubspec.yaml, pubspec.yaml
Updated Flutter/Dart dependencies for better compatibility with current state of Flutter ecosystem.
- Replaced `pedantic` with `flutter_lints` as it is deprecated for quite some time already: https://pub.dev/packages/pedantic
Note, I used not `2.0.3` version as it bumps min Flutter to 3.7.0, so stayed with `2.0.2` to have better compatibility with projects with Flutter >3.3.0
- Updated `uuid` to a range of versions for broader compatibility and because 3.x versions are compatible with 4.x versions according to README: https://pub.dev/packages/uuid#uuid
- Updated Flutter and Dart constraints to correspond to dependencies and not confuse users about package compatibility.
- Updated README to remove some outdated information
=> Update dependencies and README

android/build.gradle, android/gradle/wrapper/gradle-wrapper.properties, android/src/main/AndroidManifest.xml, android/src/main/kotlin/com/github/florent37/assets_audio_player/notification/NotificationService.kt, example/android/app/build.gradle, example/android/build.gradle, example/android/gradle/wrapper/gradle-wrapper.properties, pubspec.yaml
Adding foreground service type as it is required now in Android 14:
https://developer.android.com/about/versions/14/changes/fgs-types-required#use-cases
Had to bump `compileSDK` to use the new permission in the AndroidManifest. 
Additionally bumped version for Gradle plugin and Gradle wrapper to be on par with other plugins, like Flutterfire that already moved to AGP 8 completely.
Finally, this PR also closes https://github.com/florent37/Flutter-AssetsAudioPlayer/issues/814 and allows users to use the plugin in projects with AGP 8. However, due to how old some dependencies in the example app I couldn't move it to AGP 8, so only plugin uses it now.
=> Add permission for service needed by latest Android versions
