android/build.gradle

the old gradle doesn,t work any more, so I updated it.

Just Updated Gradle

---

.idea/libraries/Dart_SDK.xml
.idea/runConfigurations/example_lib_main_dart.xml
.idea/workspace.xml
android/build.gradle
assets_audio_player.iml
example/android/app/build.gradle
example/android/build.gradle
example/android/gradle.properties
example/android/gradle/wrapper/gradle-wrapper.properties
example/ios/Flutter/Flutter.podspec
example/ios/Podfile
example/ios/Runner.xcodeproj/project.pbxproj
example/lib/main.dart
example/pubspec.yaml
ios/Classes/SwiftAssetsAudioPlayerPlugin.swift
lib/assets_audio_player.dart
pubspec.yaml

I needed this to upgrade to the latest RxDart. There were several other upgrades I either found necessary or thought would be helpful.
asset loading update follows:
https://flutter.dev/docs/development/ui/assets-and-images
migrate example to androidx, rebuild ios pods to latest format
simplify audio asset arguments to platform to take advantage of built-in asset lookup API
bumped version

upgrade to latest rxdart, rework platform asset loading to follow docs

---

.idea/libraries/Dart_Packages.xml
.idea/libraries/Flutter_Plugins.xml
.idea/workspace.xml
example/ios/Flutter/flutter_export_environment.sh
example/ios/Runner.xcodeproj/project.pbxproj
example/ios/Runner/AppDelegate.swift
ios/Classes/AssetsAudioPlayer.swift

Solved the issue number #1
I just updated the app to swift 5 and the error is not coming anymore and i can play the audio seamlessly

updated to swift 5

---

android/build.gradle
android/src/main/kotlin/com/github/florent37/assets_audio_player/AssetsAudioPlayerPlugin.kt
android/src/main/kotlin/com/github/florent37/assets_audio_player/Player.kt
android/src/main/kotlin/com/github/florent37/assets_audio_player/StopWhenCall.kt
android/src/main/kotlin/com/github/florent37/assets_audio_player/StopWhenCallAudioFocus.kt

implemented using auto focus, need to try it

stop on call

---

android/src/main/kotlin/com/github/florent37/assets_audio_player/AssetsAudioPlayerPlugin.kt
android/src/main/kotlin/com/github/florent37/assets_audio_player/Player.kt
assets_audio_player_web/lib/web/abstract_web_player.dart
assets_audio_player_web/lib/web/web_player_html.dart
ios/Classes/Music.swift
lib/assets_audio_player.dart

Add parameter playSpeed in open(playList)

---

CHANGELOG.md
README.md
android/src/main/AndroidManifest.xml
android/src/main/kotlin/com/github/florent37/assets_audio_player/AssetsAudioPlayerPlugin.kt
android/src/main/kotlin/com/github/florent37/assets_audio_player/notification/MediaButtonsReciever.kt
android/src/main/kotlin/com/github/florent37/assets_audio_player/notification/NotificationManager.kt
assets_audio_player_web/CHANGELOG.md
assets_audio_player_web/pubspec.yaml

works on android (only if notification is enabled)

handle bluetooth actions

---

android/src/main/kotlin/com/github/florent37/assets_audio_player/AssetsAudioPlayerPlugin.kt
android/src/main/kotlin/com/github/florent37/assets_audio_player/Player.kt
ios/Classes/Music.swift
lib/src/assets_audio_player.dart

The seek method only supports seconds, this enable millsecond seek in android

android support millsecond seek

---

README.md

update version  from ^1.6.4+3 to ^1.6.4+4 last version

Update Package dependencies version

---

android/src/main/AndroidManifest.xml
android/src/main/kotlin/com/github/florent37/assets_audio_player/AssetsAudioPlayerPlugin.kt
android/src/main/kotlin/com/github/florent37/assets_audio_player/notification/MediaButtonsReceiver.kt
android/src/main/kotlin/com/github/florent37/assets_audio_player/notification/NotificationActionReceiver.kt
android/src/main/kotlin/com/github/florent37/assets_audio_player/notification/NotificationService.kt
android/src/main/kotlin/com/github/florent37/assets_audio_player/notification/NotificationSettings.kt
lib/src/notification.dart

This PR adds functionality to close: #146

add: ability to hide seekbar in android notification

---

android/src/main/kotlin/com/github/florent37/assets_audio_player/notification/NotificationSettings.kt
ios/Classes/Music.swift
lib/src/notification.dart

This PR adds seekbar enabled functionality on iOS too.

add: seekbar enabled functionality for ios

---

CHANGELOG.md
lib/src/assets_audio_player.dart
lib/src/playing.dart
pubspec.yaml

Adds `isBuffering` to the `RealtimePlayingInfos`

Add is buffering

---

darwin/Classes/Music.swift

Fix playing of Firebase storage signed URLs on iOS

---

lib/src/cache/cache.dart
lib/src/cache/cache_downloader.dart
lib/src/cache/cache_manager.dart
pubspec.yaml

Convert dio to http.

---

android/src/main/kotlin/com/github/florent37/assets_audio_player/playerimplem/PlayerImplemExoPlayer.kt

I have a problem. SeekTo for remote AAC files doesn't work. 
This PR solve the problem.
Please accept PR. 
Thanks.

Fix seekTo for remote AAC files

---

lib/src/assets_audio_player.dart
lib/src/network_settings.dart

Fixed a bug that prevents setting up default headers, because of const construtor and immutable map.

fixed unmutable map

---

android/src/main/kotlin/com/github/florent37/assets_audio_player/notification/NotificationService.kt

Hope it can be released to the next version, I did not find any related problems after testing

Fix #380 android.os.DeadSystemException

---

darwin/Classes/Music.swift

Fix https://github.com/florent37/Flutter-AssetsAudioPlayer/issues/425
I passed the test on iOS 10

Fix iOS 10 Crash #425

---

android/src/main/AndroidManifest.xml
android/src/main/kotlin/com/github/florent37/assets_audio_player/notification/CustomMediaButtonReceiver.kt

Fixes https://github.com/florent37/Flutter-AssetsAudioPlayer/issues/331

Fix illegal state exception on Android

---

android/build.gradle
android/gradle.properties
android/local.properties
android/src/main/kotlin/com/github/florent37/assets_audio_player/Player.kt
android/src/main/kotlin/com/github/florent37/assets_audio_player/notification/CustomMediaButtonReceiver.kt
android/src/main/kotlin/com/github/florent37/assets_audio_player/notification/ImageDownloader.kt
android/src/main/kotlin/com/github/florent37/assets_audio_player/notification/NotificationActionReceiver.kt
example/android/app/build.gradle
example/android/build.gradle
example/android/gradle.properties
example/lib/generated_plugin_registrant.dart
example/lib/main.dart

Support for android SDK level 30. 
The media controls for the notifications do not work yet. Maybe someone has an idea what the problem is?

Android API 30

---

android/src/main/kotlin/com/github/florent37/assets_audio_player/notification/NotificationService.kt

fixed no function for stopForeground

---

lib/src/assets_audio_player.dart

Fixes #519.
Thanks to @jxzy999 for fix.
I'm just opening this pull request.
Let me know if you need changes the other way around. This should work with minimal changes though.

Fixed music not auto changing in playlist

---

example/pubspec.yaml
lib/src/assets_audio_player.dart
lib/src/player_group.dart
pubspec.yaml

Update `rxdart` to `0.27.0`

---

android/src/main/AndroidManifest.xml

Android 12 (sdk 31) required to have exported flag for receiver as well

Issue-599 Fix android12 support - Added exported flag to receivers

---

android/build.gradle
android/gradle/wrapper/gradle-wrapper.properties
android/src/main/AndroidManifest.xml
android/src/main/kotlin/com/github/florent37/assets_audio_player/notification/NotificationActionReceiver.kt
android/src/main/kotlin/com/github/florent37/assets_audio_player/notification/NotificationService.kt
android/src/main/kotlin/com/github/florent37/assets_audio_player/playerimplem/PlayerImplemExoPlayer.kt
example/android/app/build.gradle
example/android/app/src/main/AndroidManifest.xml
example/android/build.gradle
example/android/gradle/wrapper/gradle-wrapper.properties
example/ios/Runner.xcodeproj/project.pbxproj
example/lib/main.dart
example/macos/Runner.xcodeproj/project.pbxproj

Known issue app crash when click media notification panel.

Android 12 Fix ( WIP)

---

lib/src/assets_audio_player.dart

Fix call to value in getCurrentAudioTitle and all below to fix #672.

---

android/src/main/kotlin/com/github/florent37/assets_audio_player/AssetsAudioPlayerPlugin.kt
example/lib/main.dart
example/lib/main_group.dart
example/lib/main_media_query.dart
example/lib/main_multiples.dart
example/lib/main_record.dart
example/lib/main_streams.dart
example/lib/main_test.dart
example/lib/player/ForwardRewindSelector.dart
example/lib/player/PlaySpeedSelector.dart
example/lib/player/PlayingControls.dart
example/lib/player/PlayingControlsSmall.dart
example/lib/player/PositionSeekWidget.dart
example/lib/player/SongsSelector.dart
example/lib/player/VolumeSelector.dart
lib/src/assets_audio_player.dart
lib/src/playing.dart

This PR fixes [ISSUE 669](https://github.com/florent37/Flutter-AssetsAudioPlayer/issues/669) and some other warnings

Fix for onNewIntent(p0: Intent) override on AssetsAudioPlayerPlugin

---

lib/src/assets_audio_player.dart

I have faced this problem too #615  and fixed it by emiting false in _buffering stream
`_isBuffering.add(false);`

Buffering always true bug fixed.

---

android/build.gradle
assets_audio_player_web/android/build.gradle
pubspec.yaml

* Widen `http` dependency range
* Add `namespace` if available - it's required for new `AGP` versions

Compatibility updates

---

android/build.gradle
android/src/main/kotlin/com/github/florent37/assets_audio_player/notification/NotificationService.kt

Fixes https://github.com/florent37/Flutter-AssetsAudioPlayer/issues/797

Fix naming

---

README.md

I've updated the readme to correspond with the change.
changed from autoPlay property to autoStart

changed autoPlay to autoStart
